# Generated by Django 5.1.3 on 2024-12-02 11:53

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre', max_length=255)),
                ('apellido', models.CharField(blank=True, default='Apellido', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='genere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, validators=[api.models.validar_rut])),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('trabajador', 'Trabajador'), ('tercero', 'Tercero')], max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(default='+56', max_length=12)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('isbn', models.CharField(max_length=15, unique=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
                ('genero', models.ManyToManyField(to='api.genere')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_caducidad', models.DateTimeField(blank=True, null=True)),
                ('aplazamientos', models.IntegerField(default=0)),
                ('devuelto', models.BooleanField(default=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
