# Generated by Django 5.1.3 on 2024-12-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_libro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='apellido',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
