# Generated by Django 5.1.3 on 2024-12-09 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuario_imagen_alter_usuario_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='apellido',
        ),
    ]
